name: Install Python dependencies
description: Install all core and optional Python dependencies
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        # Install a specific version of uv.
        version: "0.9.27"
    - name: Get Terraform Version
      id: tf_version
      run: |
        echo "value=$(cat .terraform-version)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.tf_version.outputs.value }}
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"
        cache: "pip"
        cache-dependency-path: |
          uv.lock
    - run: echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
      shell: bash
    - name: Install the project
      run: uv sync --all-extras
      shell: bash
