name: aws-complete-k8s
provider:
  name: aws
  account_id: "793009824629"
  region: "eu-central-1"
deployment:
  type: kubernetes
stack:
  - data_versioning:
      name: lakefs
  - experiment_tracking:
      name: mlflow
  - orchestrator:
      name: prefect
